#!/usr/bin/env python3
"""
Deterministic renderer: use-cases.json + process-map.json -> human Markdown views.

Appends Use cases / Gaps sections onto existing views/contexts/{slug}.md
(generated by ddd-domain-model render_domain_views.py). Writes platform-level
views/process-map.md.

Usage:
  python3 render_use_case_views.py <output_root>
  python3 render_use_case_views.py <output_root> --context analytics-etl

Do not hand-edit generated sections between the markers below.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent

UC_BEGIN = "<!-- BEGIN ddd-use-cases:generated -->"
UC_END = "<!-- END ddd-use-cases:generated -->"


def load_json(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def mermaid_id(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", text)[:48] or "n"


def esc(text: str, max_len: int = 60) -> str:
    t = (text or "").replace('"', "'").replace("\n", " ")
    if len(t) > max_len:
        t = t[: max_len - 3] + "..."
    return t


def strip_generated_section(md: str) -> str:
    if UC_BEGIN in md and UC_END in md:
        pattern = re.compile(
            re.escape(UC_BEGIN) + r".*?" + re.escape(UC_END) + r"\n?",
            re.DOTALL,
        )
        return pattern.sub("", md).rstrip() + "\n"
    # Legacy: drop from ## Use cases if already appended without markers
    if "\n## Use cases\n" in md:
        return md.split("\n## Use cases\n", 1)[0].rstrip() + "\n"
    return md.rstrip() + "\n"


def fmt_list(items: list[Any] | None) -> str:
    if not items:
        return "—"
    return ", ".join(f"`{i}`" for i in items)


def render_use_cases_section(doc: dict[str, Any]) -> str:
    slug = doc.get("context_slug", "?")
    lines = [
        UC_BEGIN,
        "",
        "## Use cases",
        "",
        f"_Generated from `contexts/{slug}/use-cases.json`. Do not edit between markers._",
        "",
        f"Status: **{doc.get('status', '?')}** | Confidence: **{doc.get('confidence', '?')}** | Updated: {doc.get('last_updated', '?')}",
        "",
        "| ID | Name | Kind | Aggregate | Actor | Trigger | Outcomes | Status |",
        "|----|------|------|-----------|-------|---------|----------|--------|",
    ]

    for uc in doc.get("use_cases") or []:
        trigger = uc.get("trigger") or {}
        outcomes = uc.get("outcomes") or {}
        ev = list(outcomes.get("domain_events") or [])
        integ = list(outcomes.get("integrations") or [])
        fail = list(outcomes.get("failure_events") or [])
        out_bits = ev + integ + ([f"!{f}" for f in fail] if fail else [])
        actor = uc.get("actor")
        actor_s = actor if actor else f"_{uc.get('actor_status', 'unknown')}_"
        lines.append(
            "| {id} | {name} | {kind} | {agg} | {actor} | {trig} | {out} | {st} |".format(
                id=uc.get("id", ""),
                name=uc.get("name", ""),
                kind=uc.get("kind", ""),
                agg=uc.get("target_aggregate") or "—",
                actor=esc(str(actor_s), 40),
                trig=esc(f"{trigger.get('type', '?')}: {trigger.get('ref') or '—'}", 48),
                out=esc(", ".join(out_bits) if out_bits else "—", 48),
                st=uc.get("status", ""),
            )
        )

    lines.extend(["", "### Detail", ""])
    for uc in doc.get("use_cases") or []:
        trigger = uc.get("trigger") or {}
        outcomes = uc.get("outcomes") or {}
        lines.append(f"#### {uc.get('id')} — {uc.get('name')}")
        lines.append("")
        if uc.get("description"):
            lines.append(uc["description"])
            lines.append("")
        lines.append(f"- **Kind:** {uc.get('kind')}")
        lines.append(
            f"- **Actor:** `{uc.get('actor')}` ({uc.get('actor_status', '?')})"
            if uc.get("actor")
            else f"- **Actor:** _unknown_ (`{uc.get('actor_status', 'unknown')}`)"
        )
        lines.append(
            f"- **Trigger:** `{trigger.get('type')}` — {trigger.get('ref') or '—'}"
        )
        lines.append(f"- **Target aggregate:** `{uc.get('target_aggregate')}`")
        lines.append(f"- **Commands:** {fmt_list(uc.get('commands_invoked'))}")
        lines.append(f"- **Queries:** {fmt_list(uc.get('queries_invoked'))}")
        lines.append(
            f"- **Domain events:** {fmt_list(outcomes.get('domain_events'))}"
        )
        lines.append(
            f"- **Integrations:** {fmt_list(outcomes.get('integrations'))}"
        )
        lines.append(
            f"- **Failure events:** {fmt_list(outcomes.get('failure_events'))}"
        )
        if uc.get("part_of_process"):
            lines.append(f"- **Process:** `{uc['part_of_process']}`")
        elif uc.get("part_of_processes"):
            lines.append(
                f"- **Processes:** {fmt_list(uc.get('part_of_processes'))}"
            )
        if uc.get("gaps"):
            lines.append(f"- **Gaps:** {fmt_list(uc.get('gaps'))}")
        if uc.get("human_correction_needed"):
            lines.append("- **Needs human correction:**")
            for h in uc["human_correction_needed"]:
                lines.append(f"  - {h}")
        lines.append("")

    gaps = doc.get("gaps") or []
    open_gaps = [g for g in gaps if g.get("status") == "open"]
    lines.extend(["## Use-case gaps", ""])
    if not gaps:
        lines.append("_None._")
        lines.append("")
    else:
        lines.append(
            f"Open: **{len(open_gaps)}** / {len(gaps)} total "
            f"({sum(1 for g in open_gaps if g.get('blocking'))} blocking)"
        )
        lines.append("")
        lines.append(
            "| ID | Type | Blocking | Status | Use case | Severity |"
        )
        lines.append(
            "|----|------|----------|--------|----------|----------|"
        )
        for g in gaps:
            rel = g.get("related") or {}
            lines.append(
                "| {id} | {gt} | {bl} | {st} | {uc} | {sev} |".format(
                    id=g.get("id", ""),
                    gt=g.get("gap_type", ""),
                    bl="yes" if g.get("blocking") else "no",
                    st=g.get("status", ""),
                    uc=rel.get("use_case_id") or "—",
                    sev=esc(g.get("severity", ""), 70),
                )
            )
        lines.append("")
        for g in open_gaps:
            hyps = g.get("candidate_hypotheses") or []
            if not hyps:
                continue
            lines.append(f"**{g.get('id')}** hypotheses:")
            for h in hyps:
                lines.append(f"- {h}")
            lines.append("")

    lines.append(UC_END)
    lines.append("")
    return "\n".join(lines)


def mermaid_state_id(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", text or "state")
    if s and s[0].isdigit():
        s = "s_" + s
    return s[:64] or "state"


def render_process_state_machine(sm: dict[str, Any]) -> list[str]:
    lines: list[str] = ["#### Process state machine", ""]
    name = sm.get("name") or "Process lifecycle"
    conf = sm.get("confidence", "?")
    status = sm.get("status", "?")
    inference = sm.get("inference", "")
    meta = f"**{name}** | status: `{status}` | confidence: `{conf}`"
    if inference:
        meta += f" | inference: `{inference}`"
    lines.append(meta)
    if sm.get("description"):
        lines.append("")
        lines.append(sm["description"])
    lines.extend(["", "```mermaid", "stateDiagram-v2"])

    initial = sm.get("initial_state")
    if initial:
        lines.append(f"  [*] --> {mermaid_state_id(initial)}")

    for st in sm.get("states") or []:
        sid = mermaid_state_id(st.get("id", "state"))
        label = esc(st.get("label") or st.get("id", ""), 28)
        if st.get("step_order") is not None:
            label = esc(f"{st['step_order']}:{label}", 32)
        lines.append(f"  {sid} : {label}")

    for tr in sm.get("transitions") or []:
        frm = tr.get("from") or ""
        to = tr.get("to") or ""
        if not frm or not to:
            continue
        bits = [tr.get("trigger") or ""]
        if tr.get("use_case_id"):
            bits.append(tr["use_case_id"])
        if tr.get("emits_event"):
            bits.append(f"→{tr['emits_event']}")
        label = esc(" / ".join(b for b in bits if b), 40)
        arrow = f"  {mermaid_state_id(frm)} --> {mermaid_state_id(to)}"
        if label:
            arrow += f" : {label}"
        lines.append(arrow)

    for term in sm.get("terminal_states") or []:
        lines.append(f"  {mermaid_state_id(term)} --> [*]")

    lines.extend(["```", ""])
    return lines


def render_process_map(doc: dict[str, Any]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Process map — {doc.get('platform_name', 'platform')}",
        "",
        "Human-readable projection of `process-map.json`. **Do not edit by hand** — regenerate with:",
        "",
        "```bash",
        f"python3 {SCRIPT_DIR / 'render_use_case_views.py'} <output_root>",
        "```",
        "",
        f"Status: **{doc.get('status', '?')}** | Confidence: **{doc.get('confidence', '?')}** | Updated: {doc.get('last_updated', '?')}",
        "",
        f"Generated: {now}",
        "",
        "## Processes",
        "",
    ]

    for proc in doc.get("processes") or []:
        pid = proc.get("id", "?")
        lines.append(f"### {pid} — {proc.get('name', '')}")
        lines.append("")
        if proc.get("description"):
            lines.append(proc["description"])
            lines.append("")
        lines.append(
            f"Contexts: {', '.join(f'`{c}`' for c in proc.get('contexts_involved') or [])} | "
            f"Status: **{proc.get('status', '?')}** | Confidence: **{proc.get('confidence', '?')}**"
        )
        lines.append("")
        lines.append("| Order | Context | Use case | Triggered by | Produces | Integration |")
        lines.append("|-------|---------|----------|--------------|----------|-------------|")
        for s in sorted(proc.get("steps") or [], key=lambda x: x.get("order") or 0):
            lines.append(
                "| {o} | `{ctx}` | `{uc}` | {tb} | {pe} | {wi} |".format(
                    o=s.get("order", ""),
                    ctx=s.get("context_slug", ""),
                    uc=s.get("use_case_id") or "_pending_",
                    tb=f"`{s['triggered_by_event']}`" if s.get("triggered_by_event") else "—",
                    pe=f"`{s['produces_event']}`" if s.get("produces_event") else "—",
                    wi=esc(s.get("waits_for_integration") or "—", 40),
                )
            )
        lines.append("")
        lines.append("```mermaid")
        lines.append("flowchart LR")
        steps = sorted(proc.get("steps") or [], key=lambda x: x.get("order") or 0)
        prev = None
        for s in steps:
            oid = mermaid_id(f"{pid}_{s.get('order')}_{s.get('context_slug')}")
            uc = s.get("use_case_id") or "?"
            label = esc(
                f"{s.get('order')}. {s.get('context_slug')}\\n{uc}",
                50,
            )
            shape_open, shape_close = ("[", "]") if s.get("use_case_id") else ("[[", "]]")
            # mermaid stadium for pending
            if not s.get("use_case_id"):
                lines.append(f'  {oid}("{label}")')
            else:
                lines.append(f'  {oid}["{label}"]')
            if prev is not None:
                edge = ""
                if s.get("triggered_by_event"):
                    edge = f"|{esc(s['triggered_by_event'], 24)}|"
                elif s.get("produces_event") and prev:
                    # unlabeled sequential
                    edge = ""
                lines.append(f"  {prev} -->{edge} {oid}")
            prev = oid
        # annotate produced events as notes via dashed nodes for terminal events
        for s in steps:
            if not s.get("produces_event"):
                continue
            oid = mermaid_id(f"{pid}_{s.get('order')}_{s.get('context_slug')}")
            eid = mermaid_id(f"{pid}_ev_{s.get('order')}_{s['produces_event']}")
            lines.append(f'  {eid}(["{esc(s["produces_event"], 32)}"])')
            lines.append(f"  {oid} -.-> {eid}")
        lines.append("```")
        lines.append("")

        sm = proc.get("state_machine")
        if sm and (sm.get("states") or sm.get("transitions")):
            lines.extend(render_process_state_machine(sm))

        if proc.get("gaps"):
            lines.append(f"Process gaps: {fmt_list(proc.get('gaps'))}")
            lines.append("")

    platform_gaps = doc.get("gaps") or []
    if platform_gaps:
        lines.extend(["## Cross-context gaps", ""])
        lines.append("| ID | Type | Status | Context | Severity |")
        lines.append("|----|------|--------|---------|----------|")
        for g in platform_gaps:
            rel = g.get("related") or {}
            lines.append(
                "| {id} | {gt} | {st} | `{ctx}` | {sev} |".format(
                    id=g.get("id", ""),
                    gt=g.get("gap_type", ""),
                    st=g.get("status", ""),
                    ctx=rel.get("context_slug", ""),
                    sev=esc(g.get("severity", ""), 70),
                )
            )
        lines.append("")

    return "\n".join(lines)


def update_readme_index(views: Path, platform_name: str) -> None:
    readme = views / "README.md"
    if not readme.is_file():
        return
    text = readme.read_text(encoding="utf-8")
    link = "- [Process map](process-map.md) — cross-context use-case flows"
    if "process-map.md" in text:
        return
    # Insert after glossary line if present
    if "- [Glossary](glossary.md)" in text:
        text = text.replace(
            "- [Glossary](glossary.md) — ubiquitous language",
            "- [Glossary](glossary.md) — ubiquitous language\n"
            + link,
        )
    else:
        text += f"\n{link}\n"
    # note use-case regeneration
    note = (
        "\nUse-case sections inside each context page and `process-map.md` are "
        "regenerated by:\n\n```bash\n"
        f"python3 {SCRIPT_DIR / 'render_use_case_views.py'} {views.parent}\n"
        "```\n"
    )
    if "render_use_case_views.py" not in text:
        text = text.rstrip() + "\n" + note
    readme.write_text(text if text.endswith("\n") else text + "\n", encoding="utf-8")


def render_all(root: Path, only_contexts: list[str] | None = None) -> list[str]:
    warnings: list[str] = []
    views = root / "views"
    contexts_views = views / "contexts"
    views.mkdir(parents=True, exist_ok=True)
    contexts_views.mkdir(parents=True, exist_ok=True)

    contexts_dir = root / "contexts"
    slugs: list[str] = []
    if contexts_dir.is_dir():
        for d in sorted(contexts_dir.iterdir()):
            if d.is_dir():
                slugs.append(d.name)

    if only_contexts:
        missing = set(only_contexts) - set(slugs)
        for m in sorted(missing):
            warnings.append(f"unknown context: {m}")
        slugs = [s for s in slugs if s in only_contexts]

    for slug in slugs:
        uc_path = contexts_dir / slug / "use-cases.json"
        md_path = contexts_views / f"{slug}.md"
        uc_doc = load_json(uc_path)
        if uc_doc is None:
            warnings.append(f"{slug}: no use-cases.json (skipped appendix)")
            continue
        if md_path.is_file():
            base = strip_generated_section(md_path.read_text(encoding="utf-8"))
        else:
            warnings.append(f"{slug}: missing views/contexts/{slug}.md — writing use-case stub only")
            base = f"# {slug}\n\n_Domain view missing; run render_domain_views.py first._\n"
        section = render_use_cases_section(uc_doc)
        md_path.write_text(base.rstrip() + "\n\n" + section, encoding="utf-8")

    pm = load_json(root / "process-map.json")
    if pm is None:
        warnings.append("process-map.json missing — skipped views/process-map.md")
    else:
        (views / "process-map.md").write_text(render_process_map(pm) + "\n", encoding="utf-8")
        platform = pm.get("platform_name", "platform")
        update_readme_index(views, platform)

    return warnings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output_root", type=Path)
    parser.add_argument("--context", action="append", dest="contexts", default=[])
    args = parser.parse_args()

    root = args.output_root.resolve()
    if not root.is_dir():
        print(f"ERROR: not a directory: {root}", file=sys.stderr)
        return 2

    warnings = render_all(root, args.contexts or None)
    for w in warnings:
        print(f"WARN: {w}")
    print(f"Rendered use-case views under {root / 'views'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
